### PR TITLE
Add error callback to connect method

### PR DESCRIPTION
**Pull request by VladLupashevskyi**

### CODE REVIEW

**Comment by Rapsssito** [comment]
@VladLupashevskyi, thanks for the PR! Unfortunately it cannot be merged, since it will break the cross-platform API with NodeJS. `react-native-tcp-socket` mimics Node's net API, so every interface must match net's.

In this case, take a look at the [connect method](https://nodejs.org/api/net.html#net_socket_connect). As it is stated in the docs, if an error occurs, the `error` event will be emitted. Adding a new parameter is not necessary.

**Comment by VladLupashevskyi** [comment]
@Rapsssito thanks you the quick reply.

I'm not familiar very much with NodeJS net API, but I see your point.

However unexpected issue still can happen. Take a look at this example:

```js
const connect = createConnection(...);
// Delay 500ms
connect.on('error', console.error);
```

In this case the error can happen before handler is attached.

I assume in NodeJS net library one can instantiate the "connect" object and attach a handler BEFORE actually initializing connection, so it's always guaranteed that error handler will be called on error.

Taking in account cross-platform support we can do the following:

1. Revert changes in `connect` function in TcpSocket.js.
2. Introduce new function in index.js like:

```js
function createConnectionOrError(options, success, error) {
    const tcpSocket = new Socket(getInstanceNumber(), nativeEventEmitter);
    tcpSocket.on('error', error);
    return tcpSocket.connect(options, success);
}
```

@Rapsssito What do you think about it?

**Comment by Rapsssito** [comment]
@VladLupashevskyi I have just pushed a new version. Now, you are able to instantiate a Socket without connecting, so you should be able to add the error listener before connecting. Check out the example code for more info.

**Comment by Rapsssito** [comment]
@VladLupashevskyi I have just pushed a new version. Now, you are able to instantiate a Socket without connecting, so you should be able to add the error listener before connecting. Check out the example code for more info.

**Pull request closed without merging**
